grupo13/projeto-av1/config/routes.rb
Rails.application.routes.draw do
  resources :videos

  root 'videos#index'

end

grupo13/projeto-av1/app/models/video.rb
class Video < ActiveRecord::Base
  def next
    Video.where("id > ?", id).first
  end

  def prev
    Video.where("id < ?", id).last
  end
end

grupo13/projeto-av1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

grupo13/projeto-av1/app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @videos = Video.all

    @next_video = @video.next
    @prev_video = @video.prev
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :title)
    end
end

grupo13/projeto-av1/app/helpers/application_helper.rb
module ApplicationHelper
end

grupo13/projeto-av1/app/helpers/videos_helper.rb
module VideosHelper
end

grupo13/projeto-av1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjetoAv1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


   <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
          
</head>
<body>

   <nav>
    <div class="nav-wrapper">
      <%= link_to image_tag("logo-learnpedia-transp.png", width: "53px", boder: 0 ), root_path %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="<%= root_path %>"><i class="material-icons">ondemand_video</i></a></li>
        <li><%= link_to new_video_path do %>
  <i class="material-icons">playlist_add</i>
<% end %>
        
      </ul>
    </div>
  </nav>

  <div class="row">
    <div class="col m10 offset-m1">
      <%= yield %>
    </div>
  </div>

  <script>
    $(".button-collapse").sideNav();
  </script>

</body>
</html>

grupo13/projeto-av1/app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.text_field :wistia, :placeholder => 'Link', :length => '10' %>
  </div>
  <div class="input-field">
    <%= f.text_field :title, :placeholder => 'Título', :length => '20' %>
  </div>
  <div class="input-field">
    <%= f.text_area :description, :placeholder => 'Descrição', :length => '800', :class => 'materialize-textarea' %>
  </div>
  <button class="btn waves-effect waves-light" type="submit" name="action">Enviar</button>
  <a href="<%= videos_path %>" class="btn waves-effect waves-light" name="action">Voltar</a>
<% end %>

grupo13/projeto-av1/app/views/videos/edit.html.erb
<h1>Editar Video</h1>

<div class="card">
  <div class="card-content">
    <%= render 'form' %>
  </div>
</div>

grupo13/projeto-av1/app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Videos</h1>

<%= link_to new_video_path, :class => 'btn-floating btn-large waves-effect waves-light red' do %>
  <i class="large material-icons">add</i>
<% end %>

<ul class="collapsible" data-collapsible="accordion">
  <% @videos.each do |video| %>
    <li>
      <div class="collapsible-header">
        <i class="small material-icons">list</i>
        <%= link_to video.title, video %>
        <span class="right">
          <%= link_to edit_video_path(video) do %>
            <i class="small material-icons">mode_edit</i>
          <% end %>
          <%= link_to video, method: :delete, data: { confirm: 'Tem certeza?' } do %>
            <i class="small material-icons">delete_forever</i>
          <% end %>
        </span>
       <div class="collapsible-body"><p><%= video.description %></p></div>
      </div>
    </li>
  <% end %>
</ul>

<script>
  $(document).ready(function(){
    $('.collapsible').collapsible();
  });
</script>

grupo13/projeto-av1/app/views/videos/new.html.erb
<h1>Novo Video</h1>

<div class="card">
  <div class="card-content">
    <%= render 'form' %>
  </div>
</div>

grupo13/projeto-av1/app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col md3">
    <div class="collection">
      <% @videos.each do |video| %>
        <%= link_to video.title, video, :class => 'collection-item' %>
      <% end %>
    </div>
  </div>
  <div class="col m9">
    <div class="card blue-gray darken-1"> 
    <span class="card-title"><center><%= @video.title %></center></span><p>
      <div class="card-image">
        <div id="wistia_<%= @video.wistia %>"></div>
      </div>
      <div class="card-content black-text">
        <p>Descrição: <%= @video.description %></p>
        <p>Video id: <%= @video.wistia %></p>
        <p>Data da publicação: <%= @video.created_at.strftime('%d/%m/%Y') %></p>
        <br>
        <div class="row">
          <div class="col m9">
            <div class="card-panel grey lighten-5 z-depth-1">
              <div class="row valign-wapper">
                <% if @video.id == 1 %>
                  <div class="col m2">
                   <%= image_tag "diego.jpg", class: "circle responsive-img" %>
                  </div>
                 <div class="col m9">
                    <span class="black-text">
                     Autor: Diego Maciel de Amorim<p>
                     Assunto do vídeo: Como levantar uma aplicação ruby no Heroku
                    </span>
                  </div>
                <% elsif @video.id == 2 %>
                  <div class="col m2">
                   <%= image_tag "marcio.jpg", class: "circle responsive-img" %>
                  </div>
                 <div class="col m9">
                    <span class="black-text">
                     Autor: Márcio Mota<p>
                     Assunto do vídeo: Introdução básica ao Heroku
                    </span>
                  </div>
                <% else %>
                <div class="col m2">
                   <%= image_tag "jvt.jpg", class: "circle responsive-img" %>
                  </div>
                 <div class="col m9">
                    <span class="black-text">
                     Autor: João Victor Tavares<p>
                     Assunto do vídeo:
                    </span>
                  </div>
                <% end %>
              </div>
            </div>
          </div> 
        </div>
      </div>
      <div class="card-action">
        <%= link_to "Anterior", @prev_video %>
        <span class="right">
         <%= link_to "Próximo", @next_video if !@next_video.nil? %>
        </span>
      </div>
    </div>
  </div>
</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.10&appId=2006572269579407";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#abcd" data-width="100%" data-numposts="1"></div>

<script src="//fast.wistia.net/static/E-v1.js" ></script>

<script>
  wistiaEmbed = Wistia.embed("<%= @video.wistia %>", {
    videoFoam: true
  });
</script>

<center><a href="<%= videos_path %>" class="btn waves-effect waves-light" name="action">Voltar</a></center>